project:
  type: book

book:
  title: "The Soybean Expression Atlas v2: code and data"
  author: 
    - name: Fabricio Almeida-Silva
      orcid: 0000-0002-5314-2964
  date: "2023"
  chapters:
    - index.qmd
    - chapters/01_creating_the_SEA_v2.qmd
    - chapters/02_analyzing_quantitative_data.qmd
    - chapters/03_exploring_summary_stats.qmd
    - chapters/04_create_app_data_directory.qmd
    - chapters/05_global_expression_analyses.qmd
    - chapters/appendices.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo

editor: 
  mode: source